### ISSUE TITLE
FR: GPT-4

### ISSUE THREAD

**Issue by JCharante** [clairefro/obsidian-chat-cbt-plugin#2]
Hi there, great plugin so far. I wish there was a dropdown box to select between GPT 3.5 (which this uses, at least according to my platform billing page) and GPT 4. I wouldn't mind paying extra for the extra intelligence in the responses.

**Comment by JCharante** [comment]
I know 3.5 is slower, but I just tend to use gpt4 for everything and generally can feel a difference when using gpt3.5. I'm not sure if I find it lacking, I have to use the plugin more

**Comment by JCharante** [comment]
*typo fix, meant to say 4 is slower

**Comment by kityr** [comment]
> But I'm open to making model selection for both OpenAI and Ollama a feature.

Yes, that would be great! Mistral, which ChatCBT uses, doesn't fit into my VRAM, while llama2 and some other 3.8gb models do; would be great to be able to choose a smaller model to take advantage of GPU inference

**Comment by JCharante** [comment]
Awesome, thank you!

**Comment by clairefro** [comment]
Model override now available in [release version 1.0.3](https://github.com/clairefro/obsidian-chat-cbt-plugin/releases/tag/1.0.3)

Simple [update your Obsidian plugins](https://help.obsidian.md/Extending+Obsidian/Community+plugins#:~:text=Update%20plugins&text=To%20update%20all%20your%20plugins,are%20available%2C%20select%20Update%20all.) to access
