### ISSUE TITLE
Invalid initialization vecto

### ISSUE THREAD

**Issue by mbrydak** [clairefro/obsidian-chat-cbt-plugin#3]
HI!

I am also experiencing the error mentioned in title, same as the other person from hackernews.

I'd like to make it easier in reproducing the error, so in my fork of the repo (https://github.com/mbrydak/obsidian-chat-cbt-plugin) you can find `flake.nix` and `flake.lock` files, which will allow you to reproduce the environemnt in which I've built the plugin. 

You can see info on how to run it and how does it work here: https://zero-to-nix.com/start/nix-develop 

for now it wil reproduce only my node environment, but in an hour or two i will also attach obsidian and ollama :)

Also, for what it's worth: the plain ollama plugin does not throw this type of error for me, and works just fine: https://github.com/hinterdupfinger/obsidian-ollama

**Comment by clairefro** [comment]
Hey there! Really appreciate the repro. I'm on a business trip this week, but will deep dive this next week 

Thanks for the reference to a working ollama example as well

**Comment by kityr** [comment]
I'm experiencing the same error on my desktop, any way I could capture logs? Ollama logs don't seem to have anything relevant

**Comment by clairefro** [comment]
Thanks for the reports. 

To confirm, for those experiencing the error, how are you starting the Ollama server? 

I'm wondering if this is related to OLLAMA_ORIGINS is related to the error, since @mbrydak isn't having issue with the other Ollama obsidian plugin, which uses the same obsidian `requestUrl` method as `chat-cbt`

`OLLAMA_ORIGINS="*" OLLAMA_HOST="0.0.0.0:11434" ollama serve`

**Comment by clairefro** [comment]
Ah.. I figured this out. It is related to the `cryptr` library attempting to encode a missing OpenAI API Key. I will fix this

As a temporary fix to use immediately: type something random in the `Open AI API Key` setting in ChatCBT settings

<img width="890" alt="image" src="https://github.com/clairefro/obsidian-chat-cbt-plugin/assets/9841162/5e6f3493-bd7a-4368-affb-4c75d9cd675c">

**Comment by kityr** [comment]
> As a temporary fix to use immediately: type something random in the `Open AI API Key` setting in ChatCBT settings

Yes, that worked, thanks!

**Comment by clairefro** [comment]
Thanks both - fixed with #4 

To fix, [update](https://help.obsidian.md/Extending+Obsidian/Community+plugins) your ChatCBT version to latest (1.0.2)

> 1. Open Settings.
> 2. Under Community plugins → Current plugins, select Check for updates.
> 3. Under Installed plugins, select Update next to the plugin you want to update.
