### ISSUE TITLE
Super cool plugin!

### ISSUE THREAD

**Issue by dougkeiller** [clairefro/obsidian-chat-cbt-plugin#5]
Hi,

This is a great concept. Would love to know more about what's happening under the hood.

Of course, there are other frameworks in addition to CGT, eg IPNB, that would be interesting to explore as well.

Thanks, Doug

**Comment by clairefro** [comment]
Hi Doug, thanks for the kind words. 

The whole thing runs off a single LLM prompt to respond to user messages. You can see the exact prompt [here](https://github.com/clairefro/obsidian-chat-cbt-plugin/blob/main/src/prompts/system.ts). There is a small [additional prompt](https://github.com/clairefro/obsidian-chat-cbt-plugin/blob/main/src/prompts/system.ts) for summarizing the conversation into a table.

You're welcome to fork the plugin and edit the prompt for local use if you'd like to experiment with other instructions. Happy to hear how it goes if you do
